### ISSUE TITLE
UWP manifest element & attribute names shouldn't be translated

### ISSUE THREAD

**Issue by lechacon** [MicrosoftDocs/winrt-related.es-es#1]
Or it should at least include the original name along with the localization. In this page I'm told that an element is called "UAP: regla" and it has attributes "Corresponde", "Tipo" and "WindowsRuntimeAccess", but it only works in the manifest file if written in English as "uap:Rule", "Match" and "Type". The text is also inconsistent sometimes calling the attribute "Corresponde" and sometimes "Match", but never saying they are the same thing.

This is not exclusive to this page, it happens across all the manifest schema reference.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para la vinculación de problemas de docs.microsoft.com ➟ GitHub.*

* ID: 7dde6871-d322-4d98-9cda-afaa1bb91c19
* Version Independent ID: c433f317-60d8-3fef-64f2-32c656b8b465
* Content: [UAP: regla (Windows 10) - Windows UWP applications](https://docs.microsoft.com/es-mx/uwp/schemas/appxpackage/uapmanifestschema/element-uap-rule)
* Content Source: [winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap-rule.md](https://github.com/MicrosoftDocs/winrt-related.es-es/blob/docs/winrt-related-src/schemas/appxpackage/uapmanifestschema/element-uap-rule.md)
* Product: **uwp**
* Technology: **winrt-reference**
* GitHub Login: @GrantMeStrength
* Microsoft Alias: **jken**

**Comment by srvbpigh** [comment]
Hello, @lechacon
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @lechacon 

Thank you for your contribution.

Contributions on translation problems against machine translated content are currently not accepted.

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations.

Human translated topics can be distinguished from machine translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file.

Many thanks for your support.

Microsoft DOCS Global Experience Team

**Comment by lechacon** [comment]
I see, I didn't realize it was machine translated.
Thank you.
